# Analyzing Bikeshare Data - Final Project for GA data science course

This is Jupyter Ipython Notebook file ( 2 of 2) for my final project

This code contains the data modeling

# Importing Packages and Libraries

In [1]:
# Import packages and functions
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cross_validation import cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LogisticRegression
from sklearn.cross_validation import train_test_split
from sklearn.linear_model import Ridge
from sklearn.linear_model import RidgeCV 
from sklearn import metrics

C:\Users\piyus\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

# Read data file

In [2]:
bike = pd.read_csv(r'C:\Users\piyus\Desktop\GA_Project\Data\2017_bikedata\bike.csv', parse_dates=['start_time'])

In [3]:
bike.head()

,trip_duration,trip_seconds,start_time,dummy_hour,start_hour,stop_time,start_station_id,start_station_name,start_station_latitude,start_station_longitude,...,user_type,birth_year,gender,age,humidity,temp,pressure,description,wind_direction,wind_speed
0,11.33,680,2017-01-01 00:00:00,0:00,0,1/1/2017 0:11,3226,W 82 St & Central Park West,40.782750,-73.971370,...,Subscriber,1965,2,52,44,278.76,1014,broken clouds,220,4
1,21.37,1282,2017-01-01 00:00:00,0:00,0,1/1/2017 0:22,3263,Cooper Square & E 7 St,40.729236,-73.990868,...,Subscriber,1987,2,30,44,278.76,1014,broken clouds,220,4
2,11.10,666,2017-01-01 00:01:00,0:01,0,1/1/2017 0:12,3163,Central Park West & W 68 St,40.773407,-73.977825,...,Subscriber,2000,1,17,44,278.76,1014,broken clouds,220,4
3,9.32,559,2017-01-01 00:05:00,0:05,0,1/1/2017 0:14,499,Broadway & W 60 St,40.769155,-73.981918,...,Subscriber,1973,1,44,44,278.76,1014,broken clouds,220,4
4,13.77,826,2017-01-01 00:05:00,0:05,0,1/1/2017 0:19,362,Broadway & W 37 St,40.751726,-73.987535,...,Subscriber,1977,2,40,44,278.76,1014,broken clouds,220,4

# Exploratory Data Analysis

In [4]:
bike.columns

Index(['trip_duration', 'trip_seconds', 'start_time', 'dummy_hour',
       'start_hour', 'stop_time', 'start_station_id', 'start_station_name',
       'start_station_latitude', 'start_station_longitude', 'end_station_id',
       'end_station_name', 'end_station_latitude', 'end_station_longitude',
       'bike_id', 'user_type', 'birth_year', 'gender', 'age', 'humidity',
       'temp', 'pressure', 'description', 'wind_direction', 'wind_speed'],
      dtype='object')

In [5]:
# Check for missing values
bike.isnull().sum()

trip_duration              0
trip_seconds               0
start_time                 0
dummy_hour                 0
start_hour                 0
stop_time                  0
start_station_id           0
start_station_name         0
start_station_latitude     0
start_station_longitude    0
end_station_id             0
end_station_name           0
end_station_latitude       0
end_station_longitude      0
bike_id                    0
user_type                  0
birth_year                 0
gender                     0
age                        0
humidity                   0
temp                       0
pressure                   0
description                0
wind_direction             0
wind_speed                 0
dtype: int64

In [6]:
bike.describe()

,trip_duration,trip_seconds,start_hour,start_station_id,start_station_latitude,start_station_longitude,end_station_id,end_station_latitude,end_station_longitude,bike_id,birth_year,gender,age,humidity,temp,pressure,wind_direction,wind_speed
count,20529.000000,20529.000000,20529.000000,20529.000000,20529.000000,20529.000000,20529.000000,20529.000000,20529.000000,20529.000000,20529.000000,20529.000000,20529.000000,20529.000000,20529.000000,20529.000000,20529.000000,20529.000000
mean,11.688135,701.288811,13.662039,1347.267573,40.734617,-73.984036,1348.221297,40.734408,-73.984277,22220.098008,1977.163622,1.246919,39.836378,58.832530,277.618642,1024.315797,201.901115,3.058064
std,19.111869,1146.711617,5.213800,1336.251284,0.029159,0.016884,1338.762929,0.028963,0.016872,4147.171958,12.640831,0.444140,12.640831,20.410654,2.693564,6.704186,114.832380,1.409293
min,1.020000,61.000000,0.000000,72.000000,40.661063,-74.017134,72.000000,40.661063,-74.017134,14529.000000,1885.000000,0.000000,17.000000,31.000000,272.720000,1012.000000,30.000000,1.000000
25%,5.130000,308.000000,11.000000,351.000000,40.717227,-73.995299,350.000000,40.717400,-73.995960,18384.000000,1968.000000,1.000000,30.000000,44.000000,275.530000,1020.000000,75.000000,2.000000
50%,8.220000,493.000000,14.000000,482.000000,40.734011,-73.986905,482.000000,40.733812,-73.987030,23431.000000,1980.000000,1.000000,37.000000,55.000000,277.980000,1023.000000,220.000000,3.000000
75%,14.130000,848.000000,17.000000,3140.000000,40.752554,-73.976049,3140.000000,40.751873,-73.976056,25975.000000,1987.000000,2.000000,49.000000,80.000000,279.600000,1031.000000,310.000000,4.000000
max,1109.370000,66562.000000,23.000000,3440.000000,40.804213,-73.929891,3440.000000,40.804213,-73.929891,27325.000000,2000.000000,2.000000,132.000000,100.000000,281.610000,1033.000000,357.000000,7.000000

In [7]:
# Trip duration mean
bike.trip_duration.mean()

11.688135320765683

In [8]:
bike.bike_id.value_counts()

27226    26
25812    22
27183    22
25739    20
23369    20
24936    20
27292    20
26092    19
23381    19
25152    19
22458    19
26512    19
25421    18
26692    18
25458    18
25223    18
25780    18
26896    18
25487    18
27079    18
25135    18
23068    18
25147    18
26437    18
27277    17
22108    17
27152    17
26593    17
25202    17
25491    17
         ..
20108     1
16034     1
16050     1
18141     1
20340     1
25705     1
17501     1
16534     1
15106     1
17005     1
14962     1
14994     1
25241     1
22853     1
17069     1
26931     1
18727     1
19196     1
15170     1
21551     1
14553     1
19308     1
15250     1
18599     1
19420     1
15330     1
25577     1
17389     1
17437     1
18189     1
Name: bike_id, Length: 4864, dtype: int64

In [9]:
bike.dtypes

trip_duration                     float64
trip_seconds                        int64
start_time                 datetime64[ns]
dummy_hour                         object
start_hour                          int64
stop_time                          object
start_station_id                    int64
start_station_name                 object
start_station_latitude            float64
start_station_longitude           float64
end_station_id                      int64
end_station_name                   object
end_station_latitude              float64
end_station_longitude             float64
bike_id                             int64
user_type                          object
birth_year                          int64
gender                              int64
age                                 int64
humidity                            int64
temp                              float64
pressure                            int64
description                        object
wind_direction                      int64
wind_speed                          int64
dtype: object

In [10]:
items_counts = bike['start_station_id'].value_counts()
max_item = items_counts.max()

In [11]:
# Which are the 5 most popular bike start stations?
bike['start_station_id'].value_counts()[0:5]

285    168
435    151
509    139
284    128
459    123
Name: start_station_id, dtype: int64

In [12]:
# Which are the 5 most popular bike end stations?
bike['end_station_id'].value_counts()[0:5]

285     160
509     150
435     145
497     131
3263    129
Name: end_station_id, dtype: int64

In [13]:
# Top 5 Bike ID's?
bike['bike_id'].value_counts()[0:5]

27226    26
25812    22
27183    22
25739    20
23369    20
Name: bike_id, dtype: int64

In [14]:
# Grouping Age by Gender
bike['age'].value_counts()
bike.groupby('age').gender.count()

age
17      28
18      79
19      81
20     120
21     151
22     154
23     269
24     388
25     589
26     672
27     833
28     760
29     860
30     780
31     794
32     868
33     762
34     698
35     639
36     578
37     511
38     508
39     420
40     468
41     450
42     380
43     350
44     351
45     399
46     380
      ...
58     344
59     228
60     203
61     193
62     182
63     206
64     191
65     104
66      94
67     100
68      78
69      69
70      34
71      35
72      24
73      18
74      17
75      25
76      15
77      13
78       2
79       9
81       1
83       7
85       3
91       1
94       1
117      1
131      5
132      5
Name: gender, Length: 71, dtype: int64

In [15]:
# Descriptive statistics for trip duration
bike.trip_duration.describe()

count    20529.000000
mean        11.688135
std         19.111869
min          1.020000
25%          5.130000
50%          8.220000
75%         14.130000
max       1109.370000
Name: trip_duration, dtype: float64

In [16]:
# Count of each unique Bike ID
bike.bike_id.value_counts()

27226    26
25812    22
27183    22
25739    20
23369    20
24936    20
27292    20
26092    19
23381    19
25152    19
22458    19
26512    19
25421    18
26692    18
25458    18
25223    18
25780    18
26896    18
25487    18
27079    18
25135    18
23068    18
25147    18
26437    18
27277    17
22108    17
27152    17
26593    17
25202    17
25491    17
         ..
20108     1
16034     1
16050     1
18141     1
20340     1
25705     1
17501     1
16534     1
15106     1
17005     1
14962     1
14994     1
25241     1
22853     1
17069     1
26931     1
18727     1
19196     1
15170     1
21551     1
14553     1
19308     1
15250     1
18599     1
19420     1
15330     1
25577     1
17389     1
17437     1
18189     1
Name: bike_id, Length: 4864, dtype: int64

In [17]:
# Group trip duration by gender
bike.groupby(by='gender', axis = 0).trip_duration.mean()

gender
0     9.411466
1    11.145618
2    13.332407
Name: trip_duration, dtype: float64

In [18]:
# Correlation
bike.corr()

,trip_duration,trip_seconds,start_hour,start_station_id,start_station_latitude,start_station_longitude,end_station_id,end_station_latitude,end_station_longitude,bike_id,birth_year,gender,age,humidity,temp,pressure,wind_direction,wind_speed
trip_duration,1.000000,1.000000,0.006508,0.023078,0.026418,0.014557,0.024641,0.021918,0.005373,-0.000984,-0.024832,0.050443,0.024832,-0.053853,0.062661,-0.068731,0.064196,0.006842
trip_seconds,1.000000,1.000000,0.006509,0.023080,0.026420,0.014558,0.024642,0.021919,0.005373,-0.000984,-0.024832,0.050444,0.024832,-0.053856,0.062663,-0.068733,0.064198,0.006841
start_hour,0.006508,0.006509,1.000000,-0.019688,-0.008142,-0.028058,-0.019306,-0.013919,-0.003762,0.018656,0.033138,0.002548,-0.033138,0.053271,0.360434,0.280936,0.066904,0.311008
start_station_id,0.023078,0.023080,-0.019688,1.000000,0.156954,0.470766,0.467859,0.111773,0.396984,-0.030456,-0.019495,0.020973,0.019495,-0.018511,0.009531,-0.025319,0.014412,0.004958
start_station_latitude,0.026418,0.026420,-0.008142,0.156954,1.000000,0.188602,0.104146,0.867951,0.143747,-0.004856,-0.060972,-0.028992,0.060972,0.009279,-0.006131,0.006135,-0.004433,-0.003111
start_station_longitude,0.014557,0.014558,-0.028058,0.470766,0.188602,1.000000,0.388790,0.138124,0.711013,-0.028804,0.077056,-0.010733,-0.077056,0.001705,-0.006280,-0.015538,-0.003316,-0.009164
end_station_id,0.024641,0.024642,-0.019306,0.467859,0.104146,0.388790,1.000000,0.154571,0.464316,-0.029756,-0.012817,0.024773,0.012817,-0.003065,-0.000686,-0.021140,0.001953,-0.008944
end_station_latitude,0.021918,0.021919,-0.013919,0.111773,0.867951,0.138124,0.154571,1.000000,0.205628,-0.002191,-0.059194,-0.032675,0.059194,0.007577,-0.016999,0.011198,-0.009057,-0.006882
end_station_longitude,0.005373,0.005373,-0.003762,0.396984,0.143747,0.711013,0.464316,0.205628,1.000000,-0.019628,0.075014,-0.015675,-0.075014,0.005386,0.011888,-0.008017,0.000601,0.007201
bike_id,-0.000984,-0.000984,0.018656,-0.030456,-0.004856,-0.028804,-0.029756,-0.002191,-0.019628,1.000000,0.053554,-0.062702,-0.053554,-0.002489,0.019572,0.001027,0.009340,0.002403
birth_year,-0.024832,-0.024832,0.033138,-0.019495,-0.060972,0.077056,-0.012817,-0.059194,0.075014,0.053554,1.000000,-0.008316,-1.000000,0.029837,0.009276,0.042241,-0.019525,0.028644
gender,0.050443,0.050444,0.002548,0.020973,-0.028992,-0.010733,0.024773,-0.032675,-0.015675,-0.062702,-0.008316,1.000000,0.008316,-0.045946,0.026054,-0.046034,0.035521,0.014450
age,0.024832,0.024832,-0.033138,0.019495,0.060972,-0.077056,0.012817,0.059194,-0.075014,-0.053554,-1.000000,0.008316,1.000000,-0.029837,-0.009276,-0.042241,0.019525,-0.028644
humidity,-0.053853,-0.053856,0.053271,-0.018511,0.009279,0.001705,-0.003065,0.007577,0.005386,-0.002489,0.029837,-0.045946,-0.029837,1.000000,-0.681324,0.639367,-0.746417,-0.208973
temp,0.062661,0.062663,0.360434,0.009531,-0.006131,-0.006280,-0.000686,-0.016999,0.011888,0.019572,0.009276,0.026054,-0.009276,-0.681324,1.000000,-0.679417,0.794753,0.369055
pressure,-0.068731,-0.068733,0.280936,-0.025319,0.006135,-0.015538,-0.021140,0.011198,-0.008017,0.001027,0.042241,-0.046034,-0.042241,0.639367,-0.679417,1.000000,-0.645334,-0.053448
wind_direction,0.064196,0.064198,0.066904,0.014412,-0.004433,-0.003316,0.001953,-0.009057,0.000601,0.009340,-0.019525,0.035521,0.019525,-0.746417,0.794753,-0.645334,1.000000,0.146744
wind_speed,0.006842,0.006841,0.311008,0.004958,-0.003111,-0.009164,-0.008944,-0.006882,0.007201,0.002403,0.028644,0.014450,-0.028644,-0.208973,0.369055,-0.053448,0.146744,1.000000

In [19]:
# Trip Duration mean for every 'user_type'
bike.groupby('user_type').trip_duration.mean()

user_type
Customer      46.750417
Subscriber    11.605962
Name: trip_duration, dtype: float64

In [20]:
# Trip_Duration mean for every 'hour'
bike.groupby('start_hour').trip_duration.mean()

start_hour
0     13.648844
1     10.631317
2     10.774967
3     10.107512
4      8.873070
5     13.011557
6      9.800000
7      9.891036
8     11.632561
9     10.046032
10    10.486194
11    10.698812
12    12.247908
13    12.606946
14    13.311275
15    13.086661
16    12.780850
17    11.314067
18    11.229976
19    11.265506
20    11.278618
21    10.026003
22    11.484766
23    12.019580
Name: trip_duration, dtype: float64

# Linear Regression Model

I began trying to predict age using trip_duration as a feature but it did not seem like a good predictor so I tried to use other fields as features

In [21]:
# Create X and y
feature_cols = ['trip_duration']
X = bike[feature_cols]
y = bike.age

In [22]:
# Instantiate & fit
linreg = LinearRegression()
linreg.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [23]:
# Print the coefficients
print(linreg.intercept_)
print(linreg.coef_)

39.64440786967066
[0.01642434]

In [24]:
# Calculate the prediction
linreg.intercept_ + linreg.coef_*100

array([41.28684212])

In [25]:
# Using the predict method
linreg.predict(100)

array([41.28684212])

# Linear Regression Model - This is the main model for the features I finalized

Predicting trip duration using user type and start hour as features

In [26]:
# Convert user_type to float
bike["Is_Subscriber"] = bike['user_type'].map({'Customer':0, 'Subscriber':1})

# Train Test Split

In [27]:
# Linear model - Using Trip_Duration as the response and Is-Subscriber and Start_Hour as the features

# create X and y
feature_cols = ['start_hour', 'Is_Subscriber']
X = bike[feature_cols]
y = bike.trip_duration

# Train test split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 1)

In [28]:
bike.head()

,trip_duration,trip_seconds,start_time,dummy_hour,start_hour,stop_time,start_station_id,start_station_name,start_station_latitude,start_station_longitude,...,birth_year,gender,age,humidity,temp,pressure,description,wind_direction,wind_speed,Is_Subscriber
0,11.33,680,2017-01-01 00:00:00,0:00,0,1/1/2017 0:11,3226,W 82 St & Central Park West,40.782750,-73.971370,...,1965,2,52,44,278.76,1014,broken clouds,220,4,1
1,21.37,1282,2017-01-01 00:00:00,0:00,0,1/1/2017 0:22,3263,Cooper Square & E 7 St,40.729236,-73.990868,...,1987,2,30,44,278.76,1014,broken clouds,220,4,1
2,11.10,666,2017-01-01 00:01:00,0:01,0,1/1/2017 0:12,3163,Central Park West & W 68 St,40.773407,-73.977825,...,2000,1,17,44,278.76,1014,broken clouds,220,4,1
3,9.32,559,2017-01-01 00:05:00,0:05,0,1/1/2017 0:14,499,Broadway & W 60 St,40.769155,-73.981918,...,1973,1,44,44,278.76,1014,broken clouds,220,4,1
4,13.77,826,2017-01-01 00:05:00,0:05,0,1/1/2017 0:19,362,Broadway & W 37 St,40.751726,-73.987535,...,1977,2,40,44,278.76,1014,broken clouds,220,4,1

In [29]:
# Fitting a linear regression model and print coefficients
linreg = LinearRegression()
linreg.fit(X, y)
linreg.coef_

array([ 2.70560102e-02, -3.51731434e+01])

In [30]:
# 10 MSE scores by cross validation
scores = cross_val_score(linreg, X, y, cv=10, scoring='neg_mean_squared_error')

In [31]:
np.mean(np.sqrt(-scores))

17.28497067683454

In [32]:
treereg = DecisionTreeRegressor(max_depth=1, random_state=1)
scores = cross_val_score(treereg, X, y, cv=10, scoring='neg_mean_squared_error')
np.mean(np.sqrt(-scores))

17.273463730248295

In [33]:
treereg.fit(X,y)
pd.DataFrame(list(zip(feature_cols,treereg.feature_importances_)))

               0    1
0     start_hour  0.0
1  Is_Subscriber  1.0

# Random Forest Regressor

In [34]:
# Import class, instantiate estimator, fit with all data
rfreg = RandomForestRegressor(n_estimators=200, max_features=2, oob_score=True, random_state=1)
rfreg.fit(X_train, y_train)

# Caluclate classification accuracy
print((rfreg.oob_score_))
print(len(feature_cols))
print(rfreg.feature_importances_)

-0.00031638946062018114
2
[0.8226445 0.1773555]

In [35]:
scores = cross_val_score(rfreg, X, y, cv=10, scoring='neg_mean_squared_error')
np.mean(np.sqrt(-scores))

17.790179063388074

In [36]:
y_train

12615    22.15
3691     15.35
2838      3.13
6237     10.13
14361     3.00
18564     4.10
13408     2.48
4549      7.72
16258     5.18
13347     2.35
14945     9.47
8246      7.32
436       6.13
4036     12.25
16363     7.37
12069    16.85
2673      7.22
10172    30.88
20406    11.63
12896     3.42
19415    13.67
15492     6.73
2021      6.43
12482     6.58
4179     38.45
1628      9.10
6587     15.93
3013      3.48
6790     21.68
1246     21.60
         ...
9529     13.62
3606      9.92
19261    23.27
4415     42.50
1031     10.72
6285      2.63
1110      4.37
18272     5.60
11742    10.63
17137    24.63
19433     2.17
16946    44.93
4764      2.93
19946     6.50
8444     32.23
18900    16.03
2962     20.53
12645    37.87
3462      6.58
10989    30.02
7751     25.85
16332     6.17
144       8.55
19279     4.33
7813      9.60
10955     2.77
17289    11.90
5192     11.15
12172     6.22
235       2.50
Name: trip_duration, Length: 15396, dtype: float64

# Ridge Regression Model

In [37]:
rreg = Ridge(alpha=0.1, normalize=True) 
rreg.fit(X_train, y_train) 
rreg.coef_ 
preds = rreg.predict(X_test) 
print ('RMSE.(Ridge reg.) =', np.sqrt(metrics.mean_squared_error(y_test, preds)))

# Calculate accuracy score
preds = [int(y) for y in preds]
y_test = [int(y) for y in y_test]
print (metrics.accuracy_score(y_test, preds))

RMSE.(Ridge reg.) = 12.173072762029047
0.030391583869082407

In [38]:
alpha_range = 10.**np.arange(-2, 3) 
rregcv = RidgeCV(normalize = True, scoring = 'mean_squared_error', alphas = alpha_range) 
rregcv.fit(X_train, y_train) 
print (rregcv.alpha_) 
preds = rregcv.predict(X_test) 
print ('RMSE (Ridge CV reg.) =', np.sqrt(metrics.mean_squared_error(y_test, preds)))

0.1
RMSE (Ridge CV reg.) = 12.195654501369402

C:\Users\piyus\Anaconda3\lib\site-packages\sklearn\metrics\scorer.py:100: DeprecationWarning: Scoring method mean_squared_error was renamed to neg_mean_squared_error in version 0.18 and will be removed in 0.20.
  sample_weight=sample_weight)
C:\Users\piyus\Anaconda3\lib\site-packages\sklearn\metrics\scorer.py:100: DeprecationWarning: Scoring method mean_squared_error was renamed to neg_mean_squared_error in version 0.18 and will be removed in 0.20.
  sample_weight=sample_weight)
C:\Users\piyus\Anaconda3\lib\site-packages\sklearn\metrics\scorer.py:100: DeprecationWarning: Scoring method mean_squared_error was renamed to neg_mean_squared_error in version 0.18 and will be removed in 0.20.
  sample_weight=sample_weight)
C:\Users\piyus\Anaconda3\lib\site-packages\sklearn\metrics\scorer.py:100: DeprecationWarning: Scoring method mean_squared_error was renamed to neg_mean_squared_error in version 0.18 and will be removed in 0.20.
  sample_weight=sample_weight)
C:\Users\piyus\Anaconda3\lib\site-packages\sklearn\metrics\scorer.py:100: DeprecationWarning: Scoring method mean_squared_error was renamed to neg_mean_squared_error in version 0.18 and will be removed in 0.20.
  sample_weight=sample_weight)